### ISSUE TITLE
UseBuseinssManagers default set to True

### ISSUE THREAD

**Issue by markreyndev** [Concentra/Foundation#1]
ISSUE:
When using the QueryContainer without the BusinessManagers the error below is thrown.

WORKAROUND:
Set UseBuseinssManagers to false

ERROR:
Value cannot be null.
Parameter name: key

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.ArgumentNullException: Value cannot be null.
Parameter name: key

**Comment by ghost** [comment]
And correct the spelling of the method...

**Comment by markreyndev** [comment]
I'm sure someone has fixed this by now :D
